// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaeBddMXvhfgTY36ZrjgU6a8kr6XNSxwA',
    appId: '1:909028439771:web:1d469547478a3a33b0fefe',
    messagingSenderId: '909028439771',
    projectId: 'dzidzai',
    authDomain: 'dzidzai.firebaseapp.com',
    storageBucket: 'dzidzai.appspot.com',
    measurementId: 'G-8H0ETZKDML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_gy0VuqiQN-LTvE2FAHb1u6rcKVPiPBg',
    appId: '1:909028439771:android:a344fc137f01bc88b0fefe',
    messagingSenderId: '909028439771',
    projectId: 'dzidzai',
    storageBucket: 'dzidzai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm70pDL0unz5bCDa5LtARDJ5hzvbPT4GI',
    appId: '1:909028439771:ios:fa26ae1840585672b0fefe',
    messagingSenderId: '909028439771',
    projectId: 'dzidzai',
    storageBucket: 'dzidzai.appspot.com',
    iosBundleId: 'com.example.dzidzaiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm70pDL0unz5bCDa5LtARDJ5hzvbPT4GI',
    appId: '1:909028439771:ios:fa26ae1840585672b0fefe',
    messagingSenderId: '909028439771',
    projectId: 'dzidzai',
    storageBucket: 'dzidzai.appspot.com',
    iosBundleId: 'com.example.dzidzaiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaeBddMXvhfgTY36ZrjgU6a8kr6XNSxwA',
    appId: '1:909028439771:web:f0d3481e19798a5cb0fefe',
    messagingSenderId: '909028439771',
    projectId: 'dzidzai',
    authDomain: 'dzidzai.firebaseapp.com',
    storageBucket: 'dzidzai.appspot.com',
    measurementId: 'G-S7Y09GF4JG',
  );

}